export const GET_LIST = "GET_LIST";
export const GET_LIST_SUCCESS = "GET_LIST_SUCCESS";
export const GET_LIST_ERROR = "GET_LIST_ERROR";
export const GET_LIST_FAIL = "GET_LIST_FAIL";
export const POST_FEEDBACK = "POST_FEEDBACK";
export const POST_FEEDBACK_SUCCESS = "POST_FEEDBACK_SUCCESS";
export const POST_FEEDBACK_ERROR = "POST_FEEDBACK_ERROR";
